package:
  name: conda-disable-init
  version: 1.0

source:
  path: ../

build:
  script: $PYTHON -m pip install --no-deps .

requirements:
  host:
    - python >=3.8

  run:
    - conda
    - python >=3.8

about:
  home: https://github.com/jennan/conda_disable_init 
  license: BSD-3-Clause
  summary: Disable conda init
